namespace StockPatternApi.Models
{
    public static class StockSymbols
    {
        public static readonly string[] Tickers =
        [
            "AAPL",
            "ABBV",
            "ALAB",
            "AMTX",
            "AMZN",
            "AVGO",
            "CAT",
            "COST",
            "CRWV",
            "CVX",
            "DE",
            "GOOG",
            "GOOGL",
            "HD",
            "HIMS",
            "IONQ",
            "JNJ",
            "JPM",
            "LLY",
            "LUCD",
            "MA",
            "MCD",
            "MSFT",
            "NVDA",
            "OKLO",
            "ORCL",
            "PEP",
            "PG",
            "QQQ",
            "QUBT",
            "RUM",
            "TSLA",
            "UNH",
            "V",
            "WMT",
            "XOM"
        ];
    }
}
